### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by sajumani** [Niyiojeyinka/PHP-Multi-Cloud-School-Management-#1]
Hi,

Am trying to run the installation url in my localhost it shows, website not created create 

![image](https://user-images.githubusercontent.com/7368727/88758540-50d23e00-d186-11ea-96bb-df1afdd6d4c9.png)

**Comment by Niyiojeyinka** [comment]
Please open the application/config/constants.php 

change the value of your base url that serve as main url of the multisite.
in your case,change 127.0.0.1 to localhost.

`defined('WEB_BASE_URL') or define('WEB_BASE_URL', '127.0.0.1'); `

**Comment by Niyiojeyinka** [comment]
alternatively ,you can update your repo. this issue had been addressed in [last commit](https://github.com/Niyiojeyinka/PHP-Multi-Cloud-School-Management-/commit/bc3104ec9eaa428655c3ff6967388acfe6b6ebe2)

**Comment by sajumani** [comment]
Yes that works!

But now am getting this, while installing

Duplicate column name 'year'

CREATE TABLE payroll_payments ( id int(11) NOT NULL AUTO_INCREMENT, staff_id varchar(128) NOT NULL, ref varchar(128) NOT NULL, session varchar(128) NOT NULL, month varchar(128) NOT NULL, year varchar(128) NOT NULL, phone int, amount DECIMAL(19,2) NOT NULL, status varchar(128), year varchar(128), time int(20), PRIMARY KEY (id) );

**Comment by sajumani** [comment]
![image](https://user-images.githubusercontent.com/7368727/88763693-2df95700-d191-11ea-8c91-349eb2adad49.png)

Parent Login Shows error; May be .htaccess issue

**Comment by Niyiojeyinka** [comment]
Please update your repo.all issue reported is now resolved

**Comment by sajumani** [comment]
Thanks it works!
